server:
  port: 8080

file:
  upload:
    image-dir: ./temp/images

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tikkle
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          mattermost:
            client-id: ${ MM_CLIENT_ID }
            client-secret: ${ MM_CLIENT_SECRET }
            scope: profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/mattermost"
            client-name: Mattermost
            client-authentication-method: client_secret_post
        provider:
          mattermost:
            authorization-uri: http://localhost:8065/oauth/authorize
            token-uri: http://localhost:8065/oauth/access_token
            user-info-uri: http://localhost:8065/api/v4/users/me
            user-name-attribute: id


  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/mymongodb?authSource=admin
      #      host: localhost
      #      port: 27017
      #      database: mymongodb
      #      username: mongoadmin
      #      password: secret
    redis:
      host: localhost
      port: 6379
      password: '' # 비밀번호 설정 필요 시 추가
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1 # 네트워크 과부하 시 해당 값을 올려 배치 처리량을 늘림
logging:
  level:
    root: INFO
    com:
      taesan:
        tikkle: DEBUG
    org.apache.kafka: ERROR
    kafka.server.KafkaConfig: ERROR
    org.springframework.security: DEBUG
